Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
5
9
0
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
5
9
0
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 20, in <module>
    print(max(lst1)) #----> error occurs becaues it is a combination of int and string
TypeError: '>' not supported between instances of 'str' and 'int'
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
-5
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 29, in <module>
    index()
NameError: name 'index' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 29, in <module>
    index()
NameError: name 'index' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
3
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
3
1
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[6, 6, 'cars', 6, 7, 8, 9, 0, 8.89, -5, 0.78]
[6, 6, 6, 7, 8, 9, 0, 8.89, -5]
[6, 6, 6, 7, 9, 0, 8.89, -5]
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[6, 6, 'cars', 6, 7, 8, 9, 0, 8.89, -5, 0.78]
[6, 6, 6, 7, 8, 9, 0, 8.89, -5]
[6, 6, 6, 7, 9, 0, 8.89, -5]
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 60, in <module>
    lst1.remove(8.85)
ValueError: list.remove(x): x not in list
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[6, 6, 'cars', 6, 7, 8, 9, 0, 8.89, -5, 0.78]
[6, 6, 6, 7, 8, 9, 0, 8.89, -5]
[6, 6, 6, 7, 9, 0, 8.89, -5]
[6, 6, 6, 7, 8, 9, 0, -5, 0.78]
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[6, 6, 'cars', 6, 7, 8, 9, 0, 8.89, -5, 0.78]
[6, 6, 6, 7, 8, 9, 0, 8.89, -5]
[6, 6, 6, 7, 9, 0, 8.89, -5]
[6, 6, 6, 7, 8, 9, 0, -5, 0.78]
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 66, in <module>
    print(l1)
NameError: name 'l1' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[6, 6, 'cars', 6, 7, 8, 9, 0, 8.89, -5, 0.78]
[6, 6, 6, 7, 8, 9, 0, 8.89, -5]
[6, 6, 6, 7, 9, 0, 8.89, -5]
[6, 6, 6, 7, 8, 9, 0, -5, 0.78]
[]
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 65, in <module>
    lst1.clear()
NameError: name 'lst1' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[]
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[]
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 72, in <module>
    print(lst1)
NameError: name 'lst1' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[]
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 72, in <module>
    print(lst1)
NameError: name 'lst1' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[]
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 71, in <module>
    print(lst1)
NameError: name 'lst1' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[]
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 70, in <module>
    del(l1)
NameError: name 'l1' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[]
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 71, in <module>
    print(lst1)
NameError: name 'lst1' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[9, 0, 8, 'p', '0', 't', 34]
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[9, 0, 8, 'p', '0', 't', 34]
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 77, in <module>
    print(l1+l2)
NameError: name 'l1' is not defined
>>> 
=============== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ===============
[9, 0, 8, 'p', '0', 't', 34]
[9, 0, 8, 'p', '0', 't', 34]
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
[6, 7, 8, 9, 3]
[6, 7, 8, 9, 3]
358764869056
358751600320
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 100, in <module>
    lst2 = copy.copy(lst1)
NameError: name 'copy' is not defined
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 100, in <module>
    lst2 = copy.copy(lst1)
NameError: name 'copy' is not defined
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
[8, 9, 0, [5, 6], [3, 2, 1], 890]
[8, 9, 0, [5, 6], [3, 2, 1]]
2
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 113, in <module>
    lst2 = copy.deepcopy(l1)
NameError: name 'l1' is not defined
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
[8, 9, 0, [5, 6], [3, 2, 1], 890]
[8, 9, 0, [5, 6], [3, 2, 1]]
2
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 115, in <module>
    print(l1)
NameError: name 'l1' is not defined
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
[8, 9, 0, [5, 6], [3, 2, 1], 890]
[8, 9, 0, [5, 6], [3, 2, 1]]
2
[8, 9, 0, [5, 6], [3, 2, 1, 'cars']]
[8, 9, 0, [5, 6], [3, 2, 1]]
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
[-6, 0, 5, 7, 9, 12, 45]
[45, 12, 9, 7, 5, 0, -6]
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 128, in <module>
    lst1.sort()
TypeError: '<' not supported between instances of 'int' and 'str'
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
[-6, 0, 5, 7, 9, 12, 45]
[45, 12, 9, 7, 5, 0, -6]
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 128, in <module>
    lst1.sort()
TypeError: '<' not supported between instances of 'int' and 'str'
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
[8, 9, 0]
[8, 9]
(8, 9, 0, 6, 7, 8)
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 199, in <module>
    sum()
TypeError: sum() takes at least 1 positional argument (0 given)
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
[8, 9, 0]
[8, 9]
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
['p', 'o', 'y']
[9, [0, 8, 7], ['p', 'o', 'y']]
[9, [0, 8, 7], ['p', 'o', 'y']]
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 148, in <module>
    lst1[-1].remove('t')
NameError: name 'lst1' is not defined
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
['p', 'o', 'y']
[9, [0, 8, 7], ['p', 'o', 'y']]
[9, [0, 8, 7], ['p', 'o', 'y']]
[8, 9, [0, 8, 7], ['p', 'o', 'y'], [8]]
[8, 9, [0, 8, 7], ['p', 'o', 'y', 8]]
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
(8, 8, 9, 6, 5.78, [9, 0], (6, 8), 'hey', (9+6j))
<class 'tuple'>
<class 'int'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
(8, 9, 0, 6, 7, 8)
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 199, in <module>
    sum()
TypeError: sum() takes at least 1 positional argument (0 given)
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
(8, 9, 0, 6, 7, 8)
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 200, in <module>
    sum()
TypeError: sum() takes at least 1 positional argument (0 given)
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 198, in <module>
    sum()
TypeError: sum() takes at least 1 positional argument (0 given)
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 198, in <module>
    sum()
TypeError: sum() takes at least 1 positional argument (0 given)
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
30
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
(0, 8, 9, 12, 89)
(89, 12, 9, 8, 0)
9
8
0
6
5
0
1
2
3
4
Traceback (most recent call last):
  File "E:/219Y1A0247/day-5 file-5/program-5.py", line 223, in <module>
    print(l1[2])
NameError: name 'l1' is not defined
>>> 
========================== RESTART: E:/219Y1A0247/day-5 file-5/program-5.py ==========================
(0, 8, 9, 12, 89)
(89, 12, 9, 8, 0)
9
8
0
6
5
0
1
2
3
4
0
>>> 
